# Generated by Django 5.1.3 on 2024-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_apt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
