# Generated by Django 5.1.3 on 2024-11-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_update',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
