# Generated by Django 5.1.3 on 2024-11-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_update_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_apt',
        ),
    ]
