# Generated by Django 5.1.3 on 2024-11-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_booking_apt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_update',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
