# Generated by Django 5.1.3 on 2024-11-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_update',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
