# Generated by Django 5.1.3 on 2024-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_update',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
