# Generated by Django 5.1.3 on 2024-11-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_update',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
