# Generated by Django 5.1.3 on 2024-11-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_client_update_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_update',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
